#VSCODE Plugin Rest Client: humao.rest-client

# Variables
@baseUrl = http://localhost:9000
@loansBaseUrl = {{baseUrl}}/loans
@securePasswordBaseUrl = {{baseUrl}}/secure-password
@pointsOfInterestBaseUrl = {{baseUrl}}/points-of-interest

@urlShortenerBaseUrl = {{baseUrl}}/url-shortener

# Requests: Desafio Loans
POST {{loansBaseUrl}}/customer-loans HTTP/1.1
Content-Type: application/json

{
    "age": 26,
    "cpf": "275.484.389-23",
    "name": "Vuxaywua Zukiagou",
    "income": 5000.00,
    "location": "SP"
}

###

# Requests: Desafio Secure Password

POST {{securePasswordBaseUrl}}/validate-password HTTP/1.1
Content-Type: application/json

{
    "password": "Ab@12345678"
}

###

POST {{securePasswordBaseUrl}}/validate-password HTTP/1.1
Content-Type: application/json

{
    "password": ""
}

###

POST {{securePasswordBaseUrl}}/validate-password HTTP/1.1
Content-Type: application/json

{
    "password": "12@@aaBB"
}

###

# Requests: Desafio Points of Interest

POST {{pointsOfInterestBaseUrl}} HTTP/1.1
Content-Type: application/json

{
    "name": "Lanchonete",
    "x": 27.00,
    "y": 12.00
}

### 

POST {{pointsOfInterestBaseUrl}} HTTP/1.1
Content-Type: application/json

{
    "name": "Posto",
    "x": 31,
    "y": 18
}

###
POST {{pointsOfInterestBaseUrl}} HTTP/1.1
Content-Type: application/json

{
    "name": "Joalheria",
    "x": 15,
    "y": 12
}

###

POST {{pointsOfInterestBaseUrl}} HTTP/1.1
Content-Type: application/json

{
    "name": "Floricultura",
    "x": 19,
    "y": 21
}

###

POST {{pointsOfInterestBaseUrl}} HTTP/1.1
Content-Type: application/json

{
    "name": "Pub",
    "x": 12,
    "y": 8
}

###

POST {{pointsOfInterestBaseUrl}} HTTP/1.1
Content-Type: application/json

{
    "name": "Supermercado",
    "x": 23,
    "y": 6
}

###

POST {{pointsOfInterestBaseUrl}} HTTP/1.1
Content-Type: application/json

{
    "name": "Churrascaria",
    "x": 28,
    "y": 2
}

### 


POST {{pointsOfInterestBaseUrl}} HTTP/1.1
Content-Type: application/json

{
    "name": "Casa",
    "x": 20,
    "y": 10
}

###

POST {{pointsOfInterestBaseUrl}} HTTP/1.1
Content-Type: application/json

{
    "name": "Casa de Amigo (Visinho)",
    "x": 21,
    "y": 11
}

###

POST {{pointsOfInterestBaseUrl}} HTTP/1.1
Content-Type: application/json

{
    "name": "Invalid",
    "x": 191,
    "y": 200
}

###

GET {{pointsOfInterestBaseUrl}} HTTP/1.1
Content-Type: application/json

### 

GET {{pointsOfInterestBaseUrl}}/near?x=20&y=10&dmax=2 HTTP/1.1
Content-Type: application/json


###

# Requests: Desafio Url Shortener

# @name urlShortenerShortenUrl
POST {{urlShortenerBaseUrl}}/shorten-url HTTP/1.1
Content-Type: application/json

{
    "url": "https://www.google.com"
}
###

# @no-redirect
GET {{urlShortenerBaseUrl}}/{{urlShortenerShortenUrl.response.body.shorten_id}} HTTP/1.1

